services:
  crud:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: registry.isagog.ai/isagog-docs:0.1.4.1
    # dev command: ["uvicorn", "isagog_docs.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]    
    # prod
    command: ["poetry", "run", "python", "start.py"]
    ports:
      - "16001:8000"
    volumes:
      - /sata/experiments/isagog-docs/uploads:/app/uploads
      - /sata/isagog-docs/ontology.ttl:/app/ontology.ttl
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_WORKERS=4
      - MONGO_URI=mongodb://admin:admin@mongo:27017/
      - MONGO_DB=dev
      - MONGO_COLLECTION=docs
      - OPENROUTER_MODEL=google/gemini-2.0-flash-001
      - UPLOAD_DIR=/app/uploads
      - ONTOLOGY_PATH=/app/ontology.ttl
      - BASE_URI=http://isagog.org/ontology
    secrets:
      - OPENROUTER_API_KEY
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # fuseki:
  #   image: secoresearch/fuseki:5.0.0
  #   ports:
  #     - "16002:3030"
  #   environment:
  #     - ADMIN_PASSWORD=PaolaBorboni007
  #     - ENABLE_UPDATE=true
  #     - ENABLE_DATA_WRITE=true
  #     - ENABLE_UPLOAD=true
  #     - JVM_ARGS=-Xmx8G
  #   volumes:
  #     - /home/mema/fuseki-base/configuration:/fuseki-base/configuration
  #     - /home/mema/fuseki-base/databases:/fuseki-base/databases
  #     - /home/mema/fuseki-base/backups:/fuseki-base/backups
  #     - /home/mema/fuseki-base/ttls:/fuseki-base/sources
  #   networks:
  #     - mema_network
  #   restart: unless-stopped

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "16003:27017"
    volumes:
      - /sata/isagog-docs/mongo/data:/data/db
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=dev

secrets:
  OPENROUTER_API_KEY:
    file: ~/.secrets/DG_OPENROUTER_API_KEY
