services:
  crud:
    build: .
    image: registry.isagog.ai/isagog-docs:0.1.1
    command: ["uvicorn", "isagog_docs.main:app", "--host", "0.0.0.0", "--port", "8000"]    
    ports:
      - "16001:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/
      - MONGODB_DB_NAME=dev
      - MONGODB_COLLECTION_NAME=docs
      - UPLOADS_DIR=/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - /sata/experiments/mongo/data:/data/db
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=dev

secrets:
  OPENROUTER_API_KEY:
    file: ~/.secrets/DG_OPENROUTER_API_KEY
