services:
  crud:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    image: registry.isagog.ai/isagog-docs:0.1.3
    # dev command: ["uvicorn", "isagog_docs.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]    
    # prod
    command: ["poetry", "run", "python", "start.py"]
    ports:
      - "16002:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - APP_WORKERS=4
      - MONGO_URI=mongodb://admin:admin@mongo:27017/
      - MONGO_DB=dev
      - MONGO_COLLECTION=docs
      - OPENROUTER_MODEL=google/gemini-2.0-flash-001
      - UPLOAD_DIR=/app/uploads
    secrets:
      - OPENROUTER_API_KEY
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - /sata/experiments/mongo/data:/data/db
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=dev

secrets:
  OPENROUTER_API_KEY:
    file: ~/.secrets/DG_OPENROUTER_API_KEY
