services:
  crud:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]    
    ports:
      - "16001:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    build: .
    command: ["poetry", "run", "python3", "src/worker.py"]
    volumes:
      - ./uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongo:27017/
      - UPLOADS_DIR=/app/uploads
    secrets:
      - OPENROUTER_API_KEY

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - /sata/experiments/mongo/data:/data/db
    command: [--auth]

secrets:
  OPENROUTER_API_KEY:
    file: ~/.secrets/DG_OPENROUTER_API_KEY
